#pragma once

#ifdef DUA_PLATFORM_WINDOWS
// GLFW
	#define DUA_RELEASE                0
	#define DUA_PRESS                  1
	#define DUA_REPEAT                 2
	#define DUA_HAT_CENTERED           0
	#define DUA_HAT_UP                 1
	#define DUA_HAT_RIGHT              2
	#define DUA_HAT_DOWN               4
	#define DUA_HAT_LEFT               8
	#define DUA_HAT_RIGHT_UP           (DUA_HAT_RIGHT | DUA_HAT_UP)
	#define DUA_HAT_RIGHT_DOWN         (DUA_HAT_RIGHT | DUA_HAT_DOWN)
	#define DUA_HAT_LEFT_UP            (DUA_HAT_LEFT  | DUA_HAT_UP)
	#define DUA_HAT_LEFT_DOWN          (DUA_HAT_LEFT  | DUA_HAT_DOWN)
	#define DUA_KEY_UNKNOWN            -1
	#define DUA_KEY_SPACE              32
	#define DUA_KEY_APOSTROPHE         39
	#define DUA_KEY_COMMA              44
	#define DUA_KEY_MINUS              45 
	#define DUA_KEY_PERIOD             46
	#define DUA_KEY_SLASH              47
	#define DUA_KEY_0                  48
	#define DUA_KEY_1                  49
	#define DUA_KEY_2                  50
	#define DUA_KEY_3                  51
	#define DUA_KEY_4                  52
	#define DUA_KEY_5                  53
	#define DUA_KEY_6                  54
	#define DUA_KEY_7                  55
	#define DUA_KEY_8                  56
	#define DUA_KEY_9                  57
	#define DUA_KEY_SEMICOLON          59
	#define DUA_KEY_EQUAL              61
	#define DUA_KEY_A                  65
	#define DUA_KEY_B                  66
	#define DUA_KEY_C                  67
	#define DUA_KEY_D                  68
	#define DUA_KEY_E                  69
	#define DUA_KEY_F                  70
	#define DUA_KEY_G                  71
	#define DUA_KEY_H                  72
	#define DUA_KEY_I                  73
	#define DUA_KEY_J                  74
	#define DUA_KEY_K                  75
	#define DUA_KEY_L                  76
	#define DUA_KEY_M                  77
	#define DUA_KEY_N                  78
	#define DUA_KEY_O                  79
	#define DUA_KEY_P                  80
	#define DUA_KEY_Q                  81
	#define DUA_KEY_R                  82
	#define DUA_KEY_S                  83
	#define DUA_KEY_T                  84
	#define DUA_KEY_U                  85
	#define DUA_KEY_V                  86
	#define DUA_KEY_W                  87
	#define DUA_KEY_X                  88
	#define DUA_KEY_Y                  89
	#define DUA_KEY_Z                  90
	#define DUA_KEY_LEFT_BRACKET       91
	#define DUA_KEY_BACKSLASH          92
	#define DUA_KEY_RIGHT_BRACKET      93
	#define DUA_KEY_GRAVE_ACCENT       96
	#define DUA_KEY_WORLD_1            161
	#define DUA_KEY_WORLD_2            162 
	#define DUA_KEY_ESCAPE             256
	#define DUA_KEY_ENTER              257
	#define DUA_KEY_TAB                258
	#define DUA_KEY_BACKSPACE          259
	#define DUA_KEY_INSERT             260
	#define DUA_KEY_DELETE             261
	#define DUA_KEY_RIGHT              262
	#define DUA_KEY_LEFT               263
	#define DUA_KEY_DOWN               264
	#define DUA_KEY_UP                 265
	#define DUA_KEY_PAGE_UP            266
	#define DUA_KEY_PAGE_DOWN          267
	#define DUA_KEY_HOME               268
	#define DUA_KEY_END                269
	#define DUA_KEY_CAPS_LOCK          280
	#define DUA_KEY_SCROLL_LOCK        281
	#define DUA_KEY_NUM_LOCK           282
	#define DUA_KEY_PRINT_SCREEN       283
	#define DUA_KEY_PAUSE              284
	#define DUA_KEY_F1                 290
	#define DUA_KEY_F2                 291
	#define DUA_KEY_F3                 292
	#define DUA_KEY_F4                 293
	#define DUA_KEY_F5                 294
	#define DUA_KEY_F6                 295
	#define DUA_KEY_F7                 296
	#define DUA_KEY_F8                 297
	#define DUA_KEY_F9                 298
	#define DUA_KEY_F10                299
	#define DUA_KEY_F11                300
	#define DUA_KEY_F12                301
	#define DUA_KEY_F13                302
	#define DUA_KEY_F14                303
	#define DUA_KEY_F15                304
	#define DUA_KEY_F16                305
	#define DUA_KEY_F17                306
	#define DUA_KEY_F18                307
	#define DUA_KEY_F19                308
	#define DUA_KEY_F20                309
	#define DUA_KEY_F21                310
	#define DUA_KEY_F22                311
	#define DUA_KEY_F23                312
	#define DUA_KEY_F24                313
	#define DUA_KEY_F25                314
	#define DUA_KEY_KP_0               320
	#define DUA_KEY_KP_1               321
	#define DUA_KEY_KP_2               322
	#define DUA_KEY_KP_3               323
	#define DUA_KEY_KP_4               324
	#define DUA_KEY_KP_5               325
	#define DUA_KEY_KP_6               326
	#define DUA_KEY_KP_7               327
	#define DUA_KEY_KP_8               328
	#define DUA_KEY_KP_9               329
	#define DUA_KEY_KP_DECIMAL         330
	#define DUA_KEY_KP_DIVIDE          331
	#define DUA_KEY_KP_MULTIPLY        332
	#define DUA_KEY_KP_SUBTRACT        333
	#define DUA_KEY_KP_ADD             334
	#define DUA_KEY_KP_ENTER           335
	#define DUA_KEY_KP_EQUAL           336
	#define DUA_KEY_LEFT_SHIFT         340
	#define DUA_KEY_LEFT_CONTROL       341
	#define DUA_KEY_LEFT_ALT           342
	#define DUA_KEY_LEFT_SUPER         343
	#define DUA_KEY_RIGHT_SHIFT        344
	#define DUA_KEY_RIGHT_CONTROL      345
	#define DUA_KEY_RIGHT_ALT          346
	#define DUA_KEY_RIGHT_SUPER        347
	#define DUA_KEY_MENU               348
	#define DUA_KEY_LAST               DUA_KEY_MENU
	#define DUA_MOD_SHIFT           0x0001
	#define DUA_MOD_CONTROL         0x0002
	#define DUA_MOD_ALT             0x0004
	#define DUA_MOD_SUPER           0x0008
	#define DUA_MOD_CAPS_LOCK       0x0010
	#define DUA_MOD_NUM_LOCK        0x0020
	#define DUA_MOUSE_BUTTON_1         0
	#define DUA_MOUSE_BUTTON_2         1
	#define DUA_MOUSE_BUTTON_3         2
	#define DUA_MOUSE_BUTTON_4         3
	#define DUA_MOUSE_BUTTON_5         4
	#define DUA_MOUSE_BUTTON_6         5
	#define DUA_MOUSE_BUTTON_7         6
	#define DUA_MOUSE_BUTTON_8         7
	#define DUA_MOUSE_BUTTON_LAST      DUA_MOUSE_BUTTON_8
	#define DUA_MOUSE_BUTTON_LEFT      DUA_MOUSE_BUTTON_1
	#define DUA_MOUSE_BUTTON_RIGHT     DUA_MOUSE_BUTTON_2
	#define DUA_MOUSE_BUTTON_MIDDLE    DUA_MOUSE_BUTTON_3
	#define DUA_JOYSTICK_1             0
	#define DUA_JOYSTICK_2             1
	#define DUA_JOYSTICK_3             2
	#define DUA_JOYSTICK_4             3
	#define DUA_JOYSTICK_5             4
	#define DUA_JOYSTICK_6             5
	#define DUA_JOYSTICK_7             6
	#define DUA_JOYSTICK_8             7
	#define DUA_JOYSTICK_9             8
	#define DUA_JOYSTICK_10            9
	#define DUA_JOYSTICK_11            10
	#define DUA_JOYSTICK_12            11
	#define DUA_JOYSTICK_13            12
	#define DUA_JOYSTICK_14            13
	#define DUA_JOYSTICK_15            14
	#define DUA_JOYSTICK_16            15
	#define DUA_JOYSTICK_LAST          DUA_JOYSTICK_16
	#define DUA_GAMEPAD_BUTTON_A               0
	#define DUA_GAMEPAD_BUTTON_B               1
	#define DUA_GAMEPAD_BUTTON_X               2
	#define DUA_GAMEPAD_BUTTON_Y               3
	#define DUA_GAMEPAD_BUTTON_LEFT_BUMPER     4
	#define DUA_GAMEPAD_BUTTON_RIGHT_BUMPER    5
	#define DUA_GAMEPAD_BUTTON_BACK            6
	#define DUA_GAMEPAD_BUTTON_START           7
	#define DUA_GAMEPAD_BUTTON_GUIDE           8
	#define DUA_GAMEPAD_BUTTON_LEFT_THUMB      9
	#define DUA_GAMEPAD_BUTTON_RIGHT_THUMB     10
	#define DUA_GAMEPAD_BUTTON_DPAD_UP         11
	#define DUA_GAMEPAD_BUTTON_DPAD_RIGHT      12
	#define DUA_GAMEPAD_BUTTON_DPAD_DOWN       13
	#define DUA_GAMEPAD_BUTTON_DPAD_LEFT       14
	#define DUA_GAMEPAD_BUTTON_LAST            DUA_GAMEPAD_BUTTON_DPAD_LEFT
	#define DUA_GAMEPAD_BUTTON_CROSS       DUA_GAMEPAD_BUTTON_A
	#define DUA_GAMEPAD_BUTTON_CIRCLE      DUA_GAMEPAD_BUTTON_B
	#define DUA_GAMEPAD_BUTTON_SQUARE      DUA_GAMEPAD_BUTTON_X
	#define DUA_GAMEPAD_BUTTON_TRIANGLE    DUA_GAMEPAD_BUTTON_Y
	#define DUA_GAMEPAD_AXIS_LEFT_X        0
	#define DUA_GAMEPAD_AXIS_LEFT_Y        1
	#define DUA_GAMEPAD_AXIS_RIGHT_X       2
	#define DUA_GAMEPAD_AXIS_RIGHT_Y       3
	#define DUA_GAMEPAD_AXIS_LEFT_TRIGGER  4
	#define DUA_GAMEPAD_AXIS_RIGHT_TRIGGER 5
	#define DUA_GAMEPAD_AXIS_LAST          DUA_GAMEPAD_AXIS_RIGHT_TRIGGER
	#define DUA_ARROW_CURSOR           0x00036001
	#define DUA_IBEAM_CURSOR           0x00036002
	#define DUA_CROSSHAIR_CURSOR       0x00036003
	#define DUA_POINTING_HAND_CURSOR   0x00036004
	#define DUA_RESIZE_EW_CURSOR       0x00036005
	#define DUA_RESIZE_NS_CURSOR       0x00036006
	#define DUA_RESIZE_NWSE_CURSOR     0x00036007
	#define DUA_RESIZE_NESW_CURSOR     0x00036008
	#define DUA_RESIZE_ALL_CURSOR      0x00036009
	#define DUA_NOT_ALLOWED_CURSOR     0x0003600A
	#define DUA_HRESIZE_CURSOR         DUA_RESIZE_EW_CURSOR
	#define DUA_VRESIZE_CURSOR         DUA_RESIZE_NS_CURSOR
	#define DUA_HAND_CURSOR            DUA_POINTING_HAND_CURSOR
	#define DUA_CONNECTED              0x00040001
	#define DUA_DISCONNECTED           0x00040002

#endif // DUA_PLATFORM_WINDOWS

